url: https://jaypey.github.io
baseurl: /

# Site settings
title: Jay Belval
email: jpbelv@domain.com
description: "Computer science student working mainly in Python."


# Team names, titles and social links
people:
- name: Jay Belval
  pic: 1
  position: Python Developer
  social:
    - title: github
      url: github.com/jaypey

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/jaypey

# Postal address (add as many lines as necessary)

# Build settings
markdown: kramdown
permalink: pretty