- name: "Python scripts"
  icon: "code"
  description: "I can make a variety of python scripts for personal or company use. Web scrapers, Twitter bot, discord bot."

- name: "Webmaster"
  icon: "laptop"
  description: "I could make the next personnalized website for your company, setting it up, hosting and maintaining it"

- name: "Any other projects"
  icon: "cogs"
  description: "I have many more skills which could be useful for your company or yourself. Take a look at my portfolio!"
